# Generated by Django 2.2.1 on 2019-06-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20190611_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintdetails',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
