# Generated by Django 2.2.1 on 2019-06-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20190611_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintdetails',
            name='complaint_file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
