# Generated by Django 2.2.1 on 2019-06-12 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20190612_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complainants',
            fields=[
                ('complainant_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('complainant_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='complaints',
            name='complainant_id',
            field=models.ForeignKey(default=234, on_delete=django.db.models.deletion.CASCADE, to='cms.Complainants'),
            preserve_default=False,
        ),
    ]
