# Generated by Django 2.2.1 on 2019-06-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20190612_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complainants',
            fields=[
                ('complainant_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('complainant_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
