# Generated by Django 2.2.1 on 2019-06-12 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_complaints_complainant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='complainant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Complainants'),
        ),
    ]
