# Generated by Django 2.2.1 on 2019-06-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20190612_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='complainants',
            name='complainant_email',
            field=models.EmailField(default='mutua@live.com', max_length=300),
        ),
    ]
