# Generated by Django 2.2.1 on 2019-06-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_complainants_complainant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='complaint_details',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='complaints',
            name='complaint_file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='complaint_type',
            field=models.CharField(default='complaint', max_length=100),
        ),
        migrations.AddField(
            model_name='complaints',
            name='reg_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ComplaintDetails',
        ),
    ]
