# Generated by Django 2.2.1 on 2019-06-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20190612_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
