# Generated by Django 2.2.1 on 2019-06-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20190612_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainants',
            name='complainant_email',
            field=models.EmailField(max_length=300),
        ),
    ]
