# Generated by Django 2.2.1 on 2019-06-14 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_auto_20190614_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='remark',
        ),
    ]
