# Generated by Django 2.2.1 on 2019-06-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_complaints_complaint_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='complaint_title',
            field=models.CharField(default='a big problem', max_length=100),
        ),
    ]
