# Generated by Django 2.2.1 on 2019-06-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20190622_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='complaint_title',
            field=models.CharField(max_length=100),
        ),
    ]
