# Generated by Django 2.2.1 on 2019-07-03 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_auto_20190702_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='department_id',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
